<a href="https://colab.research.google.com/github/VanshR04/Pytorch/blob/main/test_model_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import files

# # Upload file
# uploaded = files.upload()


In [ ]:
import pandas as pd
data = pd.read_csv('/content/housing_price_dataset.csv')

In [ ]:
data.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [ ]:
data['SquareFeet'] = (data['SquareFeet'] - data['SquareFeet'].mean())/(data['SquareFeet'].max() - data['SquareFeet'].min())

In [ ]:
data.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0    0.059843         4          1        Rural       1969  215355.283618
1    0.226426         3          2        Rural       1980  195014.221626
2   -0.073224         2          1       Suburb       1970  306891.012076
3    0.143885         2          1        Urban       1996  206786.787153
4    0.061844         5          2       Suburb       2001  272436.239065

In [ ]:
data['Bedrooms'] = (data['Bedrooms'] - data['Bedrooms'].mean())/(data['Bedrooms'].max() - data['Bedrooms'].min())

In [ ]:
data['Bathrooms'] = (data['Bathrooms'] - data['Bathrooms'].mean())/(data['Bathrooms'].max() - data['Bathrooms'].min())

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df = pd.get_dummies(df, columns=['Neighborhood'], dtype=int)

In [ ]:
df

SquareFeet  Bedrooms  Bathrooms  YearBuilt          Price  \
0        0.059843  0.167100   -0.49771       1969  215355.283618   
1        0.226426 -0.166233    0.00229       1980  195014.221626   
2       -0.073224 -0.499567   -0.49771       1970  306891.012076   
3        0.143885 -0.499567   -0.49771       1996  206786.787153   
4        0.061844  0.500433    0.00229       2001  272436.239065   
...           ...       ...        ...        ...            ...   
49995   -0.362369  0.500433    0.50229       1975  100080.865895   
49996    0.424025 -0.499567    0.00229       1988  374507.656727   
49997    0.486556  0.500433    0.50229       1962  384110.555590   
49998    0.294960  0.500433    0.00229       1984  380512.685957   
49999   -0.217296  0.500433    0.50229       2011  221618.583218   

       Neighborhood_Rural  Neighborhood_Suburb  Neighborhood_Urban  
0                       1                    0                   0  
1                       1                    0                   0  
2                       0                    1                   0  
3                       0                    0                   1  
4                       0                    1                   0  
...                   ...                  ...                 ...  
49995                   1                    0                   0  
49996                   0                    1                   0  
49997                   0                    1                   0  
49998                   1                    0                   0  
49999                   1                    0                   0  

[50000 rows x 8 columns]

In [ ]:
import torch

y = torch.tensor(df['Price'].values)

In [ ]:
y

tensor([215355.2836, 195014.2216, 306891.0121,  ..., 384110.5556,
        380512.6860, 221618.5832], dtype=torch.float64)

In [ ]:
y = (y - y.mean())/(y.max() - y.min())

In [ ]:
df = df.drop(columns = ['Price'])

In [ ]:
df

SquareFeet  Bedrooms  Bathrooms  YearBuilt  Neighborhood_Rural  \
0        0.059843  0.167100   -0.49771       1969                   1   
1        0.226426 -0.166233    0.00229       1980                   1   
2       -0.073224 -0.499567   -0.49771       1970                   0   
3        0.143885 -0.499567   -0.49771       1996                   0   
4        0.061844  0.500433    0.00229       2001                   0   
...           ...       ...        ...        ...                 ...   
49995   -0.362369  0.500433    0.50229       1975                   1   
49996    0.424025 -0.499567    0.00229       1988                   0   
49997    0.486556  0.500433    0.50229       1962                   0   
49998    0.294960  0.500433    0.00229       1984                   1   
49999   -0.217296  0.500433    0.50229       2011                   1   

       Neighborhood_Suburb  Neighborhood_Urban  
0                        0                   0  
1                        0                   0  
2                        1                   0  
3                        0                   1  
4                        1                   0  
...                    ...                 ...  
49995                    0                   0  
49996                    1                   0  
49997                    1                   0  
49998                    0                   0  
49999                    0                   0  

[50000 rows x 7 columns]

In [ ]:
data['YearBuilt'] = (data['YearBuilt'] - data['YearBuilt'].mean())/(data['YearBuilt'].max() - data['YearBuilt'].min())

In [ ]:
df['YearBuilt'] = (df['YearBuilt'] - df['YearBuilt'].mean())/(df['YearBuilt'].max() - df['YearBuilt'].min())

In [ ]:
df

SquareFeet  Bedrooms  Bathrooms  YearBuilt  Neighborhood_Rural  \
0        0.059843  0.167100   -0.49771  -0.231048                   1   
1        0.226426 -0.166233    0.00229  -0.076119                   1   
2       -0.073224 -0.499567   -0.49771  -0.216964                   0   
3        0.143885 -0.499567   -0.49771   0.149234                   0   
4        0.061844  0.500433    0.00229   0.219656                   0   
...           ...       ...        ...        ...                 ...   
49995   -0.362369  0.500433    0.50229  -0.146541                   1   
49996    0.424025 -0.499567    0.00229   0.036557                   0   
49997    0.486556  0.500433    0.50229  -0.329640                   0   
49998    0.294960  0.500433    0.00229  -0.019781                   1   
49999   -0.217296  0.500433    0.50229   0.360501                   1   

       Neighborhood_Suburb  Neighborhood_Urban  
0                        0                   0  
1                        0                   0  
2                        1                   0  
3                        0                   1  
4                        1                   0  
...                    ...                 ...  
49995                    0                   0  
49996                    1                   0  
49997                    1                   0  
49998                    0                   0  
49999                    0                   0  

[50000 rows x 7 columns]

In [ ]:
X = torch.tensor(df.values)

In [ ]:
X

tensor([[ 0.0598,  0.1671, -0.4977,  ...,  1.0000,  0.0000,  0.0000],
        [ 0.2264, -0.1662,  0.0023,  ...,  1.0000,  0.0000,  0.0000],
        [-0.0732, -0.4996, -0.4977,  ...,  0.0000,  1.0000,  0.0000],
        ...,
        [ 0.4866,  0.5004,  0.5023,  ...,  0.0000,  1.0000,  0.0000],
        [ 0.2950,  0.5004,  0.0023,  ...,  1.0000,  0.0000,  0.0000],
        [-0.2173,  0.5004,  0.5023,  ...,  1.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [ ]:
X.shape

torch.Size([50000, 7])

In [ ]:
train_ind = int(0.8 * len(X))

In [ ]:
train_ind

40000

In [ ]:
X_train, y_train, X_test, y_test = X[:train_ind], y[:train_ind], X[train_ind:], y[train_ind:]

In [ ]:
len(X_train)

40000

In [ ]:
from torch import nn

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.layer = nn.Linear(in_features = 7,
                           out_features = 1)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.layer(x)


In [ ]:
torch.manual_seed(42)
model = LinearRegressionModel()

In [ ]:
model.state_dict()

OrderedDict([('layer.weight',
              tensor([[ 0.2890,  0.3137, -0.0885,  0.3472, -0.0828,  0.0763, -0.1840]])),
             ('layer.bias', tensor([0.2220]))])

In [ ]:
from torch import optim
loss = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1000, gamma=0.05)

In [ ]:
model.state_dict()



OrderedDict([('layer.weight',
              tensor([[ 0.2890,  0.3137, -0.0885,  0.3472, -0.0828,  0.0763, -0.1840]])),
             ('layer.bias', tensor([0.2220]))])

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
X_train = X_train.to(device)
y_train = y_train.to(device)
X_test = X_test.to(device)
y_test = y_test.to(device)

X_test_batch = X_test[:1000].to(device).to(torch.float32)
y_test_batch = y_test[:1000].to(device).to(torch.float32)
X_train_batch = X_train[:10000].to(device).to(torch.float32)
y_train_batch = y_train[:10000].to(device).to(torch.float32)

In [ ]:
device

device(type='cuda')

In [ ]:
X_train.device

device(type='cuda', index=0)

In [ ]:
import torch

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()


In [ ]:
epochs = 10000

loss_hist = []
ep_num = []
te = []

for epoch in range(epochs + 1):
  model.train()
  pred = model(X_train_batch)
  loss_value = loss(pred, y_train_batch)
  optimizer.zero_grad()
  loss_value.backward()
  optimizer.step()
  scheduler.step()
  model.eval()

  with torch.no_grad():
    test_pred = model(X_test_batch)
    loss_test = loss(test_pred, y_test_batch)
  if epoch%100 == 0:
    ep_num.append(epoch)
    loss_hist.append(loss)
    te.append(loss_test)
    print(f"Epoch : {epoch} | Loss : {loss_value} | Test Loss : {loss_test}")


Epoch : 0 | Loss : 0.020748373121023178 | Test Loss : 0.021788913756608963
Epoch : 100 | Loss : 0.020748082548379898 | Test Loss : 0.021788621321320534
Epoch : 200 | Loss : 0.020747803151607513 | Test Loss : 0.0217883363366127
Epoch : 300 | Loss : 0.020747529342770576 | Test Loss : 0.021788062527775764
Epoch : 400 | Loss : 0.020747268572449684 | Test Loss : 0.021787796169519424
Epoch : 500 | Loss : 0.02074701525270939 | Test Loss : 0.02178754284977913
Epoch : 600 | Loss : 0.02074676938354969 | Test Loss : 0.02178729698061943
Epoch : 700 | Loss : 0.020746534690260887 | Test Loss : 0.02178705856204033
Epoch : 800 | Loss : 0.020746305584907532 | Test Loss : 0.021786827594041824
Epoch : 900 | Loss : 0.020746085792779922 | Test Loss : 0.021786605939269066
Epoch : 1000 | Loss : 0.02074586972594261 | Test Loss : 0.021786393597722054
Epoch : 1100 | Loss : 0.020745860412716866 | Test Loss : 0.021786382421851158
Epoch : 1200 | Loss : 0.02074585109949112 | Test Loss : 0.021786371245980263
Epoch :

KeyboardInterrupt: 

In [ ]:
model.state_dict()

OrderedDict([('layer.weight',
              tensor([[ 5.8466e-03,  2.9345e-04, -2.9687e-05,  6.0500e-03, -1.0302e-01,
                       -1.0300e-01, -1.0290e-01]], device='cuda:0')),
             ('layer.bias', tensor([0.1036], device='cuda:0'))])

In [ ]:
import matplotlib.pyplot as plt

# Get model predictions
y_pred = model(X_test.to(torch.float)).cpu().detach().numpy()  # Convert tensor to NumPy
y_actual = y_test.cpu().numpy()  # Convert actual values

# Scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(y_actual, y_pred, alpha=0.6)
plt.plot([min(y_actual), max(y_actual)], [min(y_actual), max(y_actual)], 'r', linestyle="--")  # 45-degree line
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted Prices")
plt.show()


NameError: name 'model' is not defined