<a href="https://colab.research.google.com/github/VanshR04/Pytorch/blob/main/torch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [136]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [137]:
scalar.ndim

0

In [138]:
scalar.item()

7

In [139]:
vec = torch.tensor([7,7])

In [140]:
vec

tensor([7, 7])

In [141]:
vec.ndim

1

In [142]:
vec.shape

torch.Size([2])

In [143]:
matrix = torch.tensor([[1,2],[3,4]])

In [144]:
matrix.ndim

2

In [145]:
matrix

tensor([[1, 2],
        [3, 4]])

In [146]:
matrix.shape

torch.Size([2, 2])

In [147]:
matrix[0]

tensor([1, 2])

In [148]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [149]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [150]:
TENSOR.shape

torch.Size([1, 3, 3])

In [151]:
TENSOR.ndim

3

In [152]:
TENSOR[0][1]

tensor([4, 5, 6])

In [153]:
#Random tensors

In [154]:
random_tensor = torch.rand(3,4)

In [155]:
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [156]:
random_tensor.ndim

2

In [157]:
random_tensor.shape

torch.Size([3, 4])

In [158]:
image_tensor = torch.rand(size = (224,224,3))

In [159]:
image_tensor

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860],
         ...,
         [0.3421, 0.0172, 0.3031],
         [0.6576, 0.9813, 0.5840],
         [0.9902, 0.5978, 0.7888]],

        [[0.9008, 0.9180, 0.2201],
         [0.9597, 0.8029, 0.2662],
         [0.2614, 0.0806, 0.6256],
         ...,
         [0.3568, 0.1704, 0.6172],
         [0.0231, 0.6317, 0.7472],
         [0.0614, 0.1727, 0.1405]],

        [[0.9203, 0.9251, 0.5313],
         [0.9694, 0.3328, 0.0146],
         [0.6746, 0.6771, 0.9902],
         ...,
         [0.8345, 0.2273, 0.2865],
         [0.3940, 0.1418, 0.3650],
         [0.0908, 0.6902, 0.8538]],

        ...,

        [[0.5521, 0.6004, 0.1658],
         [0.1479, 0.8327, 0.2563],
         [0.1063, 0.4770, 0.2286],
         ...,
         [0.1551, 0.7881, 0.3759],
         [0.7442, 0.8621, 0.7548],
         [0.6381, 0.0106, 0.0893]],

        [[0.6170, 0.3402, 0.8306],
         [0.0705, 0.2111, 0.6203],
         [0.

In [160]:
image_tensor.ndim

3

In [161]:
image_tensor.shape

torch.Size([224, 224, 3])

In [162]:
r = torch.rand(size = (3,3))
r

tensor([[0.5745, 0.9200, 0.3230],
        [0.8613, 0.0919, 0.3102],
        [0.9536, 0.6002, 0.0351]])

In [163]:
zero = torch.zeros([224,224,3])
zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [164]:
ones = torch.ones(5, dtype=int)
ones

tensor([1, 1, 1, 1, 1])

In [165]:
ones.dtype

torch.int64

In [166]:
range = torch.arange(0,10)

In [167]:
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
range.dtype

torch.int64

In [169]:
similar_zeros = torch.zeros_like(range)

In [170]:
similar_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
similar_zeros.shape

torch.Size([10])

###Tensor Datatypes

In [172]:
tens = torch.tensor([3.0,6.0,9.0], dtype=None,
                    device=None,#cpu, cuda
                    requires_grad=False)#

In [173]:
tens

tensor([3., 6., 9.])

In [174]:
tens.dtype

torch.float32

In [175]:
tens.device

device(type='cpu')

In [176]:
tens_16 = tens.type(torch.int)

In [177]:
tens_mult = (tens * tens_16).type(torch.int)

In [178]:
tens_16.dtype

torch.int32

In [179]:
tens.dtype

torch.float32

In [180]:
tens_mult.dtype

torch.int32

In [181]:
tens_mult

tensor([ 9, 36, 81], dtype=torch.int32)

In [182]:
tes1 = torch.tensor([1,2,3])
tes2 = torch.tensor([[1],[2],[3]])
print(torch.matmul(tes1,tes2))

tensor([14])


In [183]:
x = torch.arange(0,100,10)

In [184]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [185]:
x.min()

tensor(0)

In [186]:
x.max()

tensor(90)

In [187]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [188]:
x.type(torch.float32).mean()

tensor(45.)

In [189]:
x.sum()

tensor(450)

In [190]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [191]:
x.argmin()#index of min value

tensor(0)

In [192]:
x.argmax()#index of max value

tensor(9)

In [193]:
 x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [194]:
x = torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [195]:
x.size()

torch.Size([10])

In [196]:
x_reshaped = x.reshape(1,10)

In [197]:
x_reshaped

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [198]:
z = x.view(5,2)

In [199]:
z

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [200]:
z[0,0] = 5

In [201]:
z

tensor([[ 5,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [202]:
x

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [203]:
x_stacked = torch.stack([x,x,x], 0)

In [204]:
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [205]:
x_squeezed = torch.squeeze(x_stacked)

In [206]:
x_squeezed

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [207]:
x_reshaped.squeeze()

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [208]:
squeezed = x_reshaped.squeeze()

In [209]:
unsqueezed = squeezed.unsqueeze(1)

In [210]:
squeezed.shape

torch.Size([10])

In [211]:
unsqueezed.shape

torch.Size([10, 1])

In [212]:
r = torch.rand((200,200,2))

In [213]:
r

tensor([[[0.6826, 0.3743],
         [0.5220, 0.1336],
         [0.9666, 0.9754],
         ...,
         [0.4285, 0.9068],
         [0.6739, 0.1857],
         [0.0013, 0.6637]],

        [[0.3250, 0.2551],
         [0.9134, 0.9205],
         [0.0640, 0.2996],
         ...,
         [0.7882, 0.4899],
         [0.9927, 0.4824],
         [0.1632, 0.4668]],

        [[0.1680, 0.1675],
         [0.2904, 0.8599],
         [0.0591, 0.2345],
         ...,
         [0.3739, 0.5301],
         [0.6987, 0.7448],
         [0.7439, 0.8754]],

        ...,

        [[0.3864, 0.3203],
         [0.7865, 0.7787],
         [0.6708, 0.3435],
         ...,
         [0.7331, 0.8287],
         [0.9643, 0.6978],
         [0.2888, 0.1321]],

        [[0.4624, 0.4151],
         [0.3553, 0.7087],
         [0.3719, 0.4977],
         ...,
         [0.7232, 0.6965],
         [0.8195, 0.5329],
         [0.6900, 0.5125]],

        [[0.7060, 0.5247],
         [0.0304, 0.0396],
         [0.3892, 0.3531],
         ...,
 

In [214]:
r_new = torch.permute(r,(2,1,0))

In [215]:
r_new

tensor([[[0.6826, 0.3250, 0.1680,  ..., 0.3864, 0.4624, 0.7060],
         [0.5220, 0.9134, 0.2904,  ..., 0.7865, 0.3553, 0.0304],
         [0.9666, 0.0640, 0.0591,  ..., 0.6708, 0.3719, 0.3892],
         ...,
         [0.4285, 0.7882, 0.3739,  ..., 0.7331, 0.7232, 0.1579],
         [0.6739, 0.9927, 0.6987,  ..., 0.9643, 0.8195, 0.6130],
         [0.0013, 0.1632, 0.7439,  ..., 0.2888, 0.6900, 0.5328]],

        [[0.3743, 0.2551, 0.1675,  ..., 0.3203, 0.4151, 0.5247],
         [0.1336, 0.9205, 0.8599,  ..., 0.7787, 0.7087, 0.0396],
         [0.9754, 0.2996, 0.2345,  ..., 0.3435, 0.4977, 0.3531],
         ...,
         [0.9068, 0.4899, 0.5301,  ..., 0.8287, 0.6965, 0.9272],
         [0.1857, 0.4824, 0.7448,  ..., 0.6978, 0.5329, 0.0421],
         [0.6637, 0.4668, 0.8754,  ..., 0.1321, 0.5125, 0.7896]]])

In [216]:
r.shape

torch.Size([200, 200, 2])

In [217]:
r_new.shape

torch.Size([2, 200, 200])

In [218]:
r[0,0,0] = 100

In [219]:
r

tensor([[[1.0000e+02, 3.7433e-01],
         [5.2202e-01, 1.3361e-01],
         [9.6661e-01, 9.7540e-01],
         ...,
         [4.2850e-01, 9.0679e-01],
         [6.7390e-01, 1.8571e-01],
         [1.3046e-03, 6.6374e-01]],

        [[3.2497e-01, 2.5506e-01],
         [9.1337e-01, 9.2054e-01],
         [6.3961e-02, 2.9958e-01],
         ...,
         [7.8817e-01, 4.8989e-01],
         [9.9271e-01, 4.8240e-01],
         [1.6316e-01, 4.6683e-01]],

        [[1.6805e-01, 1.6745e-01],
         [2.9038e-01, 8.5987e-01],
         [5.9062e-02, 2.3446e-01],
         ...,
         [3.7391e-01, 5.3014e-01],
         [6.9870e-01, 7.4476e-01],
         [7.4391e-01, 8.7540e-01]],

        ...,

        [[3.8643e-01, 3.2030e-01],
         [7.8653e-01, 7.7874e-01],
         [6.7077e-01, 3.4349e-01],
         ...,
         [7.3313e-01, 8.2868e-01],
         [9.6435e-01, 6.9784e-01],
         [2.8880e-01, 1.3214e-01]],

        [[4.6244e-01, 4.1510e-01],
         [3.5530e-01, 7.0874e-01],
         [3.

In [220]:
r_new

tensor([[[1.0000e+02, 3.2497e-01, 1.6805e-01,  ..., 3.8643e-01,
          4.6244e-01, 7.0601e-01],
         [5.2202e-01, 9.1337e-01, 2.9038e-01,  ..., 7.8653e-01,
          3.5530e-01, 3.0399e-02],
         [9.6661e-01, 6.3961e-02, 5.9062e-02,  ..., 6.7077e-01,
          3.7188e-01, 3.8925e-01],
         ...,
         [4.2850e-01, 7.8817e-01, 3.7391e-01,  ..., 7.3313e-01,
          7.2321e-01, 1.5785e-01],
         [6.7390e-01, 9.9271e-01, 6.9870e-01,  ..., 9.6435e-01,
          8.1951e-01, 6.1301e-01],
         [1.3046e-03, 1.6316e-01, 7.4391e-01,  ..., 2.8880e-01,
          6.8996e-01, 5.3280e-01]],

        [[3.7433e-01, 2.5506e-01, 1.6745e-01,  ..., 3.2030e-01,
          4.1510e-01, 5.2465e-01],
         [1.3361e-01, 9.2054e-01, 8.5987e-01,  ..., 7.7874e-01,
          7.0874e-01, 3.9578e-02],
         [9.7540e-01, 2.9958e-01, 2.3446e-01,  ..., 3.4349e-01,
          4.9771e-01, 3.5306e-01],
         ...,
         [9.0679e-01, 4.8989e-01, 5.3014e-01,  ..., 8.2868e-01,
          6.965

In [221]:
tens = torch.arange(1,10).reshape(1,3,3)

In [222]:
tens

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [223]:
tens.shape

torch.Size([1, 3, 3])

In [224]:
#indexing
tens[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [225]:
tens[0][0]

tensor([1, 2, 3])

In [226]:
tens[0,0]

tensor([1, 2, 3])

In [227]:
tens[0,0,0]

tensor(1)

##Pytorch tensors and numpy

In [228]:
#np array to tensor

In [229]:
array = np.arange(1.0,8.0)

In [230]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [231]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [232]:
array.dtype

dtype('float64')

In [233]:
tensor.dtype

torch.float64

In [234]:
#tensor to np

In [235]:
tensor = torch.ones(10)

In [236]:
tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [237]:
tensor.dtype

torch.float32

In [238]:
np_tensor = tensor.numpy()

In [239]:
np_tensor

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

###Reproducability

##no more random values in same environment
neural network starts with random numbers ->
performs tensor operations -> updates numbers -> repeat

##To reduce randomness in nn and pytorch, the concept of **random seed** comes into play
##What it does is 'flavour' the randomness

In [240]:
random_a = torch.rand(2,2)
random_b = torch.rand(2,2)

In [241]:
random_a

tensor([[0.3142, 0.7245],
        [0.6082, 0.9234]])

In [242]:
random_b

tensor([[0.0603, 0.7355],
        [0.3410, 0.7321]])

In [243]:
random_a == random_b

tensor([[False, False],
        [False, False]])

In [244]:
#Making random but reproducable tensors

In [245]:
import torch
randm_seed = 42


In [246]:
torch.manual_seed(randm_seed)
random_c = torch.rand(3,4)
torch.manual_seed(randm_seed)
random_d = torch.rand(3,4)

print(random_c)
print(random_d)
print(random_c == random_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##If we call the random seed before each random call, the random calls give same values as shown above

the seed affects the next line of code

###Running tensors and pytorch objects on GPU's for faster computation

##GPY = faster computation on numbers

#CUDA, NVIDIA, PyTorch

In [247]:
!nvidia-smi

Sat Feb  1 22:07:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   60C    P0             27W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [248]:
#Check GPU access by PyTorch

torch.cuda.is_available()

True

In [249]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [250]:
device

'cuda'

In [251]:
#Count number of GPU's

In [252]:
torch.cuda.device_count()

1

In [253]:
#How to actually use GPU
#put tensors and models on GPU

In [254]:
print(tensor, tensor.device)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) cpu


In [255]:
#move tensor to GPU if available

In [256]:
tensor_on_gpy = tensor.to(device)
tensor_on_gpy

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0')

In [257]:
#move tensors back to cpu



In [258]:
tensor_cpu = tensor_on_gpy.to("cpu")

In [259]:
tensor_cpu.device

device(type='cpu')

In [260]:
tensor_cpu.numpy()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

###We cannot convert a tensor on a GPU to a np array, we need to chenge it's device to CPU

In [261]:
tensor_on_gpy.cpu().numpy()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)